# Generated by Django 4.1.6 on 2023-02-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'analisis_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalisisPorTemas',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_analisis', models.TextField()),
                ('path_analisis', models.TextField(blank=True, null=True)),
                ('diccionario_analisis', models.TextField(blank=True, null=True)),
                ('actualizar', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analisis_por_temas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('poligono', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('conteo_tweet', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultados', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100)),
                ('actualizar', models.IntegerField(blank=True, null=True)),
                ('diccionario_tema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id_proceso', models.OneToOneField(db_column='id_proceso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.proceso')),
                ('id_tweet', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tweet',
                'managed': False,
            },
        ),
    ]
